/**
 * Download one document.
 *
 * THIS ROUTE IS THE SECURITY-CRITICAL HALF OF DOCUMENT UPLOAD. Two separate
 * things have to be right, and neither is optional:
 *
 * WHO. A document id is not an authorisation. It is a uuid in a URL, and URLs
 * end up in browser history, in a shared screen, in a support ticket. So the row
 * is read through the SIGNED-IN USER'S client (`locals.supabase`, set by
 * src/middleware.ts) and never through a privileged one: the RLS policy on
 * `documents` scopes it to `carrier_id in (select current_user_carriers())`, so
 * another carrier's document comes back as null — the same null a nonsense id
 * gets, which is exactly right. Nothing about the file is touched before that
 * row exists.
 *
 * This path is under /app, so the session guard in src/middleware.ts already
 * refused an anonymous request before this file ran. That guard is what makes it
 * safe to trust `locals.supabase`, and it is why this route is NOT modelled on
 * src/pages/proof/[token].astro, which is deliberately public and authenticates
 * a bearer token instead of a session.
 *
 * WHAT. Serving an uploaded file from our own origin is how stored XSS happens.
 * Every header that stops it comes from `serveHeaders` in src/lib/documents.ts —
 * nosniff, a locked-down CSP, X-Frame-Options, and a content type re-checked
 * against the accept table rather than reflected from the row. Read the note
 * there before changing a single header here.
 *
 * OPEN OR SAVE. This route used to send every file as an attachment, which meant
 * "Open" put a medical card in a Downloads folder instead of on the screen. It
 * now sends `inline` for the types that are pixels or a PDF and `attachment` for
 * everything else, and `serveHeaders` decides that from the RE-VALIDATED type,
 * never from the row's raw value.
 *
 * `?download=1` forces an attachment. THE PARAMETER ONLY EVER TIGHTENS. There is
 * deliberately no `?inline=1` and there must never be one: the disposition is a
 * security decision and a query string is written by whoever typed the URL. A
 * stranger cannot use this route to get his own file rendered as this site,
 * because he cannot get his file into the bucket in the first place — checkFile
 * refuses every executable format by its first bytes — and because the only
 * input to the decision is a column we wrote from those bytes.
 */
import type { APIRoute } from 'astro'
import { documentBucket, isStorageKey, serveHeaders } from '../../../lib/documents.ts'

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * Plain text, and the same words for every failure a stranger can provoke.
 *
 * "Not found" for a document that belongs to somebody else and "not found" for
 * one that never existed: a different answer would turn this route into a way of
 * asking whether a given id is a real document on this platform.
 */
function notFound(): Response {
  return new Response('We cannot find that file.', {
    status: 404,
    headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'private, no-store' },
  })
}

export const GET: APIRoute = async ({ params, locals, url }) => {
  const supabase = locals.supabase
  // The middleware sets this on every /app route. Without it there is no user to
  // scope the read to, so there is nothing safe to answer.
  if (!supabase) return notFound()

  const id = params.id ?? ''
  // A hand-edited id is a failed uuid cast in Postgres, not an empty result.
  if (!UUID.test(id)) return notFound()

  // No .eq('carrier_id', ...) and none is wanted: RLS is the check, and adding a
  // filter here would suggest the policy is optional.
  const { data, error } = await supabase
    .from('documents')
    .select('storage_key, file_name, content_type, byte_size')
    .eq('id', id)
    .maybeSingle()

  if (error || !data) return notFound()
  const doc = data as {
    storage_key: string
    file_name: string | null
    content_type: string | null
    byte_size: number | null
  }

  // The key was generated by newStorageKey and checked when it was written.
  // Checked again before it addresses anything: this is the only value in the
  // request path that reaches the object store, and a key that is not one of
  // ours is a row somebody wrote by another route.
  if (!isStorageKey(doc.storage_key)) return notFound()

  // The binding itself is reached inside documentBucket(), which imports
  // `cloudflare:workers` dynamically because that module does not exist outside
  // the Worker runtime. Null means the bucket is not bound at all.
  const bucket = await documentBucket()
  if (!bucket) {
    return new Response('File storage is not switched on for this site.', {
      status: 503,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'private, no-store',
      },
    })
  }

  const object = await bucket.get(doc.storage_key)
  // A row whose object is gone. Says so plainly instead of serving an empty
  // file, which would look like a document that is on file and is not.
  if (!object) {
    return new Response('That file is missing from storage. Upload it again.', {
      status: 404,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'private, no-store',
      },
    })
  }

  // Only `?download=1` is read, and it can only make the answer stricter. An
  // absent or misspelled parameter means "serve it the normal way", which for an
  // unsafe type is still an attachment.
  const headers = serveHeaders(doc, { download: url.searchParams.get('download') === '1' })
  headers.set('Content-Length', String(object.size))
  return new Response(object.body, { status: 200, headers })
}
