-- `recorded_at` could not break a tie, because it was not recording what its
-- name claims.
--
-- now() in Postgres returns the TRANSACTION start time, so every row written in
-- one transaction carries an identical recorded_at. The statement ordering then
-- fell through to occurred_on — and a typo of 2027 beat its own correction to
-- 2026, which is the exact bug this was meant to fix.
--
-- Two changes: clock_timestamp() so the column means what it says, and a
-- monotonic sequence so ordering is decidable even inside a single transaction
-- and even at the same microsecond.

alter table compliance_records
  alter column recorded_at set default clock_timestamp();

alter table compliance_records
  add column seq bigint generated by default as identity;

create index compliance_records_seq_idx on compliance_records (seq);

create or replace view current_compliance_anchors as
  select distinct on (carrier_id, subject_type, subject_id, anchor_key)
    carrier_id, subject_type, subject_id, anchor_key, occurred_on, source, id, anchor_kind
  from compliance_records
  where superseded_at is null
  order by
    carrier_id, subject_type, subject_id, anchor_key,
    -- Statement: the latest thing SAID wins, so a correction beats the typo it
    -- corrects regardless of which date is further in the future.
    (case when anchor_kind = 'statement' then seq end) desc nulls last,
    -- Occurrence: the latest time it actually HAPPENED wins.
    occurred_on desc,
    -- Final tiebreak, total and deterministic: two rows can share a date, but
    -- never a sequence number.
    seq desc;

alter view current_compliance_anchors set (security_invoker = on);
grant select on current_compliance_anchors to authenticated;
